# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efd014375bd6ab435d1e46577439ddfe273897ff70749c970fff987db66d36c7025e4ca59cc424f127dbe93d5148f40c76142bffbfb421328731382857ba73ad

test:
  secret_key_base: 4e9c4f6a956a263d80a81f36ebab032eb7ed9e7b60b1c3ad2578285ddcc11a24cf0e1e6da6576335c69a6835c4c9778944147d79b5a973da4027364859326721

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
